---
dist: bionic

language: node_js
jobs:
  include:
  - node_js: '12'
  - node_js: '14'

addons:
  apt:
    sources:
      - sourceline: 'ppa:named-data/ppa-dev'
    packages:
      - build-essential
      - clang-format-8
      - libndn-cxx-dev
      - ndnsec

cache:
  npm: false
  directories:
    - $HOME/.pnpm-store

install:
  - npm install -g coveralls pnpm

before_script:
  - npm run bootstrap

script:
  - npm run build
  - test $SKIP_LITERATE || npm run literate lint
  - test $SKIP_LITERATE || npm run literate
  - npm run lint-ci
  - npm run cover -- --colors
  - cd $TRAVIS_BUILD_DIR/integ/browser-tests && npm test
  - cd $TRAVIS_BUILD_DIR/integ/ndncxx-tests && npm test
  - cd $TRAVIS_BUILD_DIR

after_success:
  - coveralls <coverage/lcov.info
  - GTAGID=UA-935676-11 bash mk/publish-nightly.sh
  - npm run typedoc -- --gaId UA-935676-11

deploy:
  - provider: pages
    edge: true
    token: $GITHUB_TOKEN
    keep_history: false
    repo: yoursunny/NDNts-nightly
    commit_message: $TRAVIS_COMMIT $TRAVIS_BUILD_WEB_URL
    local_dir: mk/nightly-output/
    fqdn: ndnts-nightly.ndn.today
    on:
      branch: develop
      node_js: '14'
  - provider: netlify
    edge: true
    site: 8987d2bb-7638-4d6b-adff-806fe3b7309a
    auth: $NETLIFY_AUTH
    dir: docs/
    message: $TRAVIS_COMMIT
    prod: true
    on:
      branch: develop
      node_js: '14'
