---
dist: bionic

language: node_js
node_js: '12.15'

addons:
  apt:
    sources:
      - sourceline: 'ppa:named-data/ppa-dev'
    packages:
      - build-essential
      - clang-format-6.0
      - libndn-cxx-dev
      - ndnsec

cache:
  npm: false
  directories:
    - $HOME/.pnpm-store

install:
  - npm install -g coveralls pnpm verdaccio

before_script:
  - npm run bootstrap

script:
  - npm run build
  - npm run literate lint
  - npm run literate
  - npm run lint-ci
  - npm run cover -- --colors && coveralls < ./coverage/lcov.info
  - cd $TRAVIS_BUILD_DIR/integ/browser-tests && npm test
  - cd $TRAVIS_BUILD_DIR/integ/ndncxx-tests && npm test
  - cd $TRAVIS_BUILD_DIR

before_deploy:
  - npm run build -- strip
  - bash mk/publish-nightly.sh

deploy:
  - provider: netlify
    edge: true
    site: 11d6303b-b200-4b5c-b2c2-4ace41795b20
    auth: $NETLIFY_AUTH
    dir: "mk/nightly-output/"
    message: $TRAVIS_COMMIT
    prod: true
    on:
      branch: develop
