name: build
on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['12', '14', '16']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ matrix.node }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:named-data/ppa
          sudo apt-get install --no-install-recommends ndnsec
      - run: npm run bootstrap
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - name: check code style
        run: |
          npm run lint
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
      - run: npm run cover -- --colors
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.node == '16' }}
  integ:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: 16-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:named-data/ppa
          sudo apt-get install --no-install-recommends build-essential clang-format-8 libndn-cxx-dev nfd
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run literate lint
      - run: npm run literate
      - run: cd integ/browser-tests && npm test
      - run: cd integ/cxx-tests && npm test
      - name: check C++ code style
        run: |
          npm run clang-format
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
  publish:
    needs: [unittest, integ]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: 16-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm run bootstrap
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run: npm run build
      - run: bash mk/publish-nightly.sh
        env:
          GTAGID: UA-935676-11
      - run: npm run typedoc
        env:
          GTAGID: UA-935676-11
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: yoursunny/NDNts-nightly
          build_dir: ./mk/nightly-output/
          commit_message: ${{ github.sha }} ${{ github.run_id }}-${{ github.run_number }}
          fqdn: ndnts-nightly.ndn.today
        env:
          GH_PAT: ${{ secrets.NIGHTLY_ACCESS_TOKEN }}
      - uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: 8987d2bb-7638-4d6b-adff-806fe3b7309a
          build-dir: ./docs/
