name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: 14-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm run bootstrap
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run: npm run build
      - run: npm run literate
      - run: npm run lint
  unittest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: 16-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: |
          echo "deb [arch=amd64 trusted=yes] https://nfd-nightly-apt.ndn.today/ubuntu focal main" \
            | sudo tee /etc/apt/sources.list.d/nfd-nightly.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends ndnsec
      - run: npm run bootstrap
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run: npm run cover -- --colors
      - uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  integ:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: 16-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: |
          echo "deb [arch=amd64 trusted=yes] https://nfd-nightly-apt.ndn.today/ubuntu focal main" \
            | sudo tee /etc/apt/sources.list.d/nfd-nightly.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends libndn-cxx-dev nfd
      - run: npm run bootstrap
      - run: npm run build
      - name: check DefinitelyTyped dependencies
        run: node mk/check-types-dep.mjs
      - run: npm run literate lint
      - run: npm run literate
      - run: cd integ/browser-tests && npm test
      - run: cd integ/cxx-tests && npm test
      - name: check C++ code style
        run: |
          npm run clang-format
          git diff --exit-code
  publish:
    needs: [build, unittest, integ]
    if: ${{ github.repository == 'yoursunny/NDNts' && github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: 16-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm run bootstrap
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run: npm run build
      - run: bash mk/publish-nightly.sh
        env:
          GTAGID: UA-935676-11
      - run: npm run typedoc
        env:
          GTAGID: UA-935676-11
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: yoursunny/NDNts-nightly
          build_dir: ./mk/nightly-output/
          commit_message: ${{ github.sha }} ${{ github.run_id }}
          fqdn: ndnts-nightly.ndn.today
        env:
          GH_PAT: ${{ secrets.NIGHTLY_ACCESS_TOKEN }}
      - uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: 8987d2bb-7638-4d6b-adff-806fe3b7309a
          build-dir: ./docs/
